name: openwrt_cloud-build

# 触发条件
on:
  schedule:
    - cron: '0 8 * * *'  # 每天8点触发
  repository_dispatch:
  workflow_dispatch:

# 环境变量
env:
  REPO_URL: https://github.com/hanwckf/immortalwrt-mt798x  # 源代码仓库地址
  REPO_BRANCH: openwrt-21.02  # 分支名称
  FEEDS_CONF: feeds.conf.default  # 源配置文件
  CONFIG_FILE: .config  # 配置文件
  DIY_P1_SH: diy-part1.sh  # 第一部分自定义脚本
  DIY_P2_SH: diy-part2.sh  # 第二部分自定义脚本
  CLASH_CORE: clash-core.sh  # Clash 核心脚本
  UPLOAD_BIN_DIR: true  # 是否上传 bin 目录
  UPLOAD_FIRMWARE: true  # 是否上传固件
  UPLOAD_RELEASE: true  # 是否上传发布版本
  TZ: Asia/Shanghai  # 时区设置
  LAST_SHORT_HASH:  # 上次提交的短哈希值

jobs:
  build:
    runs-on: ubuntu-20.04  # 运行在 Ubuntu 20.04

    steps:
    - name: Checkout  # 检出代码
      uses: actions/checkout@v4  # 使用 actions/checkout

    - name: 配置环境  # 配置构建环境
      env:
        DEBIAN_FRONTEND: noninteractive  # 非交互式安装
      run: |
        # 清理不必要的文件和 Docker 镜像
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force -a
        # 更新软件包列表并安装依赖
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL https://is.gd/depends_ubuntu_2204) 
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        # 设置时区
        sudo timedatectl set-timezone "$TZ"
        # 创建工作目录并修改权限
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: 克隆源码  # 克隆源代码
      working-directory: /workdir
      run: |
        # 显示磁盘使用情况
        df -hT $PWD
        # 克隆仓库
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        cd openwrt
        # 获取版本信息
        useVersionInfo=$(git show -s --date=short --format="Author: %an<br/>date: %cd<br/>commit: %s<br/>commit hash: %H<br/>")
        echo "useVersionInfo=$useVersionInfo" >> $GITHUB_ENV
        echo "LAST_SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    # 检查是否需要编译
    - name: 检查是否编译
      id: checkNeed
      working-directory: /workdir
      run: |
        cd openwrt
        # 获取最新发布版本号
        LATEST_RELEASE=`curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" --silent  "https://api.github.com/repos/Sereinfy/OpenWrt-NX30Pro/releases/latest"  | jq -r .name`
        if [[ "$LATEST_RELEASE" == *"${{ env.LAST_SHORT_HASH }}"* ]]; then
          echo "already exists in the latest release, stopping compile..."
          echo "::set-output name=status::false"
        else
          echo "need compile for a new release..."
          echo "::set-output name=status::success"
        fi

    # 前置设置
    - name: 前置设置
      if: steps.checkNeed.outputs.status == 'success'
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    # 更新 feeds
    - name: Update feeds
      if: steps.checkNeed.outputs.status == 'success'
      run: cd openwrt && ./scripts/feeds update -a

    # 安装 feeds
    - name: Install feeds
      if: steps.checkNeed.outputs.status == 'success'
      run: cd openwrt && ./scripts/feeds install -a

    # 后置设置
    - name: 后置设置
      if: steps.checkNeed.outputs.status == 'success'
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    # 下载 Clash 核心
    - name: clash core Download
      if: steps.checkNeed.outputs.status == 'success'
      run: |
        [ -e files ] && mv files openwrt/files
        cd openwrt
        chmod +x $GITHUB_WORKSPACE/$CLASH_CORE && $GITHUB_WORKSPACE/$CLASH_CORE

    # 下载软件包
    - name: Download package
      if: steps.checkNeed.outputs.status == 'success'
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    # 编译源码
    - name: 编译源码
      if: steps.checkNeed.outputs.status == 'success'
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    # 显示磁盘状态
    - name: 显示磁盘状态
      if: steps.checkNeed.outputs.status == 'success' && (!cancelled())
      run: df -hT

    # 上传 bin 目录
    - name: Upload bin directory
      uses: actions/upload-artifact@v4
      if: steps.checkNeed.outputs.status == 'success' && steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin

    # 整理文件
    - name: Organize files
      id: organize
      if: steps.checkNeed.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        find . -type f ! -name '*.bin' -exec rm -f {} \;
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"
        echo "::set-output name=release_tag::$(date +"%Y-%m-%d %H%M")"

    # 计算 MD5
    - name: Calculate MD5 [计算MD5]
      if: steps.checkNeed.outputs.status == 'success'
      run: |
        cd ${{ env.FIRMWARE }} && rm -rf sha256sums
        MD5=$(md5sum * | awk '{ print $2 " " $1 }' | sed ':a;N;$!ba;s/\n/<br>/g')
        echo "MD5=$MD5" >> $GITHUB_ENV

    # 上传固件目录
    - name: Upload firmware directory
      uses: actions/upload-artifact@v4
      if: steps.checkNeed.outputs.status == 'success' && steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}
        
# 生成发布标签
- name: 生成发布标签
  id: release_tag
  if: steps.checkNeed.outputs.status == 'success'
  run: |
    DATE_PREFIX=$(date +%y%m%d)
    echo "status=success" >> $GITHUB_OUTPUT
    echo "::set-output name=date_prefix::${DATE_PREFIX}"

# 上传固件到 Release
- name: Upload OpenWrt Firmware to Release
  id: release
  uses: ncipollo/release-action@main
  if: steps.checkNeed.outputs.status == 'success' && steps.organize.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
  with:
    name: ${{ steps.organize.outputs.release_tag }}-${{ env.LAST_SHORT_HASH }}
    allowUpdates: true
    removeArtifacts: true
    tag: ${{ steps.release_tag.outputs.date_prefix }}-${{ env.LAST_SHORT_HASH }}
    commit: main
    token: ${{ secrets.GITHUB_TOKEN }}
    artifacts: ${{ env.FIRMWARE }}/*
    body: |
      - 本项目是基于Hanwckf源代码编译的固件，**适用于H3C-NX30Pro设备**
      - 内置openclash、mosdns
      - 预置`geoip.dat` `Country.mmdb` 精简版只包含 `geoip:cn` 和 `geoip:private`
        预置`geosite.dat` `Loyalsoldier`自定义版，可代替官方 `geosite.dat`
        预置`geoip-asn.dat` 只包含新增类别，不包含 `CN`
      - 默认IP：192.168.10.1
      - 默认账号：root
      - 默认密码：(空)
      - 源码更新详情[点击这里查看](https://github.com/hanwckf/immortalwrt-mt798x/commits/openwrt-21.02/) 
      - 升级更新选择sysupgrade.bin,出厂设置请刷factory.bin。
      - 升级前先下载备份，升级后还原备份后重新安装需要的插件即可。
      `md5信息`
      > ${{ env.MD5 }}

# 删除工作流运行记录
- name: Delete workflow runs
  uses: Mattraks/delete-workflow-runs@v2
  with:
    retain_days: 0
    keep_minimum_runs: 3
